services:
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports: [ "9092:9092" ]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment: [ MINIO_ROOT_USER=minio, MINIO_ROOT_PASSWORD=minio12345 ]
    ports: [ "9000:9000", "9001:9001" ]
    volumes: [ "minio_data:/data" ]

  mc:
    image: minio/mc:latest
    depends_on: [minio]
    entrypoint: /bin/sh -c "
      mc alias set local http://minio:9000 minio minio12345 &&
      mc mb -p local/streamly || true &&
      sleep 1 && echo ready
      "

  postgres:
    image: postgres:16
    environment: [ POSTGRES_DB=streamly, POSTGRES_USER=streamly, POSTGRES_PASSWORD=streamly1234 ]
    ports: [ "5432:5432" ]
    volumes: [ "pg_data:/var/lib/postgresql/data" ]

volumes: { minio_data: {}, pg_data: {} }
