server: { port: 8080 }
spring:
  application: { name: ingest-service }
  kafka: { bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}, consumer: { group-id: ingest } }
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/streamly}
    username: ${SPRING_DATASOURCE_USERNAME:streamly}
    password: ${SPRING_DATASOURCE_PASSWORD:streamly1234}
  jpa:
    hibernate: { ddl-auto: none }
    properties: { hibernate.jdbc.time_zone: UTC }
  flyway: { enabled: true }
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minio}
  secretKey: ${MINIO_SECRET_KEY:minio12345}
  bucket: ${MINIO_BUCKET:streamly}
