server: { port: 8080 }
spring:
  application: { name: transcode-service }
  kafka: { bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}, consumer: { group-id: transcode } }
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minio}
  secretKey: ${MINIO_SECRET_KEY:minio12345}
  bucket: ${MINIO_BUCKET:streamly}
